### ISSUE TITLE
I would be an amazing improvement with implementing country_select parameters

### ISSUE THREAD

**Issue by tuxtux59** [zooppa/administrate-field-country#2]
Hi,

It would be great to let users of your nice library to pass customization allowed by country_select as administrate options , I speak about `priority_countries ` or  `selected`  because for now there are your choices

Thanks

**Comment by michelegera** [comment]
Hey @tuxtux59, that makes total sense.

I’ve just released [a new version of the gem](https://rubygems.org/gems/administrate-field-country/versions/0.1.0) that lets you pass an hash of `country_select_options` which in turn gets passed to `country_select` – check out the README!
